### ISSUE TITLE
Q19 Sqlpp needs to be modified

### ISSUE THREAD

**Issue by pouriapirz** [pouriapirz/tpch-on-asterixdb#2]
2 issues with Q19-Sqlpp:

1- Compile error: 
function tpch.regexp_contains@2 is undefined 

2- Performance error:
Common filtering predicates within 3 disjunctions need to be factored out (as a tmp function) so they get applied once:

``` sql
declare function q19_tmp() {
(
    select element {'lpkey':t.l_partkey,'quantity':t.l_quantity,'extndprice':t.l_extendedprice,'discount':t.l_discount}
    from  LineItem as t
    where (((t.l_shipmode = 'AIR') or (t.l_shipmode = 'AIR REG')) and (t.l_shipinstruct = 'DELIVER IN PERSON'))
)
};
```

**Comment by sigmod** [comment]
For 1,  you need the latest master to run the function.
